### ISSUE TITLE
Play and pause feature

### ISSUE THREAD

**Issue by zeeshan27102000** [tierneytim/btAudio#19] opened 2022-05-16 15:43 UTC
Hi,

It's great library to play music through Bluetooth and it also has volume control feature. By the way, how can I add additional features like play, pause, next. There is other library available on GitHub which has these features but it utilises more space and it doesn't work when combined with other code. I want a very light library which has all these features. I just want to try adding those features/commands to this library.
Can you please guide me how to do this?

**Comment by tierneytim** [comment] 2022-06-05 21:04
thanks for the interest, I'm not sure if I will add this feature simply because I don't know how to but if you want to implement you'll have to create a callback using this [function](https://github.com/espressif/arduino-esp32/blob/8ee5f0a11e5423a018e0f89146e05074466274db/tools/sdk/esp32s3/include/bt/host/bluedroid/api/include/api/esp_avrc_api.h#L574) I think. Could you point me to the libraries that implement this?

**Comment by qwertychouskie** [comment] 2022-06-17 23:04
This issue looks like a duplicate of https://github.com/tierneytim/btAudio/issues/7, which has some working example code.

**Comment by tierneytim** [comment] 2022-06-18 09:56
In that case, consider this closed and refer you to [#7 ](https://github.com/tierneytim/btAudio/issues/7)

**Closed by tierneytim** 2022-06-18 09:56 UTC
